name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Thursday at 12:20pm UTC
  schedule:
    - cron: '20 12 * * 4'

jobs:
  ci:
    name: CI
    # Only run cron on the silverstripe account
    if: (github.event_name == 'schedule' && github.repository_owner == 'silverstripe') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # set phpunit to false to prevent automatic generation of mysql phpunit jobs
      phpunit: false
      extra_jobs: |
        - php: 8.1
          db: pgsql
          phpunit: true
          composer_args: --prefer-lowest --prefer-source
        - php: 8.1
          db: pgsql
          phpunit: true
          composer_args: --prefer-source
        - php: 8.2
          db: pgsql
          phpunit: true
          composer_args: --prefer-source

